name: Pipeline
on: pull_request
jobs:
  build:
    name: Build
    container: golang:1.13.4-buster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: CLI
        run: go build cmd/malta/main.go

  quality:
    name: Quality
    container: golangci/golangci-lint:v1.21.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Go Linter
        run: golangci-lint run ./...
